provider: gemini
model: "gemini-2.5-flash-lite"
redis_url: "redis://127.0.0.1/"
commit_format: "{type}({scope}): {message}"
log:
  path: "/var/logs/gitsc.log"
  format: "nmap"
smart_commit:
  line_threshold: 150
